### PR TITLE
Modified README.md

### PR DESCRIPTION
**Pull request by NobbZ**
I inserted some explanation about what and why.

### CODE REVIEW

**Comment by NobbZ** [comment]
Perhaps we need to talk about the wording.

I think we should never merge until at least 2 of us have agreed on that code

**Comment by deepakkumarsharma** [comment]
Okay from my side.

**Comment by gmk1217** [comment]
Agreed i created a home page with the same content.. :)



[image: --]

Mohan Krishna Gundala
[image: https://]about.me/gmk.india
<https://about.me/gmk.india?promo=email_sig>

**Comment by deepakkumarsharma** [comment]
Merging and closing issue.

**Comment by NobbZ** [comment]
@gmk1217:
> Agreed i created a home page with the same content.. :)

Where did you do that? Can you give a link to it?

**Comment by gmk1217** [comment]
i created some static pages as home page and trying link Login feature to
it..


[image: --]

Mohan Krishna Gundala
[image: https://]about.me/gmk.india
<https://about.me/gmk.india?promo=email_sig>

**Comment by NobbZ** [comment]
A static page can't be used as a target of a named route and devise requires you to redirect to root_path. Thats why I have a stub controller `welcome#index` for now with the `root`-route in my design-stubbing branch.

**Pull request merged**
