### PR TITLE
Setup Devise - Initial Stage

### PR DESCRIPTION
**Pull request by deepakkumarsharma**
Setup devise for login, register and few more.

### CODE REVIEW

**Comment by NobbZ** [comment]
Please do the necessary steps to also have `Confirmable` and `Lockable` available. I think both are essential!

**Comment by NobbZ** [comment]
I still think it was to early to merge this in. `Confirmable` and `Lockable` are essential, and in many countries you might problems with court if you don't have them. These 2 needs to get added as soon as possible! @deepakkumarsharma, can you do that?

**Comment by deepakkumarsharma** [comment]
Yes! I can give me a day. Actually I'll busy in college work but will do it by today or tomarrow for sure. `Confirmable` work is easy as I worked on it once so it will take less time but `Lockable` thing is totally new to me so this take lil bit time. Will report here when done just give me one day.

**Comment by NobbZ** [comment]
I think it is enough to prepare database for lockable and configuration. An
administration back-end for actually locking users can get added on top of
that later.
Am 10.04.2015 09:11 schrieb "ih8sum3r" <notifications@github.com>:

**Comment by deepakkumarsharma** [comment]
AFAIK devise can care of that thing. Lemme check on that and then report.

**Pull request merged**
